apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: boutique-practice
  region: ap-south-1
managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 3
    spot: true
    volumeSize: 20
